[package]
name = "schema"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {workspace = true}
sea-orm = {workspace = true}
actix-web = {workspace = true}
serde_json = {workspace = true}
tera = {workspace = true}
tokio = {workspace = true}
deadpool-redis = {workspace = true}
